export function createStyles(config) {
    return {
        chatButton: {
            position: 'fixed',
            bottom: '20px',
            right: '20px',
            zIndex: '1000',
            padding: '15px',
            border: 'none',
            borderRadius: '30px',
            background: 'radial-gradient(462.56% 102.45% at 109.47% 102.45%,#a75bff 0,#635bff 57%,#635bff 100%)',
            color: 'white',
            cursor: 'pointer',
            fontSize: '24px',
            boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
            minWidth: '60px',
            minHeight: '60px',
            transition: 'transform 0.3s ease',
            '&:hover': {
                transform: 'scale(1.1)',
            },
        },
        chatContainer: {
            position: 'fixed',
            bottom: '95px',
            right: '20px',
            width: '40vw',
            height: '50vh',
            backgroundColor: 'rgba(255, 255, 255, 0.8)',
            border: `1px solid ${config.chatBorderColor}`,
            borderRadius: '20px',
            display: 'none',
            flexDirection: 'column',
            zIndex: '1001',
            overflow: 'hidden',
            fontFamily: config.fontFamily,
            fontSize: config.fontSize,
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
            backdropFilter: 'blur(10px)',
            resize: 'both',
            minWidth: '300px',
            minHeight: '400px',
        },
        sidebarChatContainer: {
            position: 'relative',
            width: '100%',
            height: '100%',
            backgroundColor: 'rgba(255, 255, 255, 0.95)',
            border: 'none',
            borderRadius: '0',
            display: 'flex',
            flexDirection: 'column',
            zIndex: '1',
            overflow: 'hidden',
            fontFamily: config.fontFamily,
            fontSize: config.fontSize,
            boxShadow: 'none',
            backdropFilter: 'none',
            resize: 'none',
        },
        showcaseChatContainer: {
            position: 'relative',
            width: '100%',
            maxWidth: config.showcaseMaxWidth || '1024px',
            height: '600px',
            minHeight: '500px',
            backgroundColor: config.chatBackgroundColor || 'rgba(255, 255, 255, 0.95)',
            border: `1px solid ${config.chatBorderColor || 'rgba(99, 91, 255, 0.2)'}`,
            borderRadius: '24px',
            display: 'flex',
            flexDirection: 'column',
            zIndex: '1',
            overflow: 'hidden',
            fontFamily: config.fontFamily,
            fontSize: config.showcaseFontSize || '16px',
            boxShadow: '0 8px 32px rgba(99, 91, 255, 0.15)',
            backdropFilter: 'blur(10px)',
            resize: 'none',
            margin: '0 auto',
        },
        chatHeader: {
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            padding: config.mode === 'showcase' ? '20px 24px' : '15px',
            paddingLeft: config.mode === 'showcase' ? '24px' : '15px',
            //background: 'linear-gradient(to bottom, rgba(255,255,255,0.8) 0%, rgba(255,255,255,0) 10%)',
            //backdropFilter: 'blur(5px)',
            borderBottom: '1px solid rgba(99, 91, 255, 0.15)',
            position: 'sticky',
            top: 0,
            zIndex: 2,
        },
        chatTitle: {
            fontWeight: 'bold',
            fontSize: config.mode === 'showcase' ? '22px' : '20px',
            color: '#333',
            flex: 1,
            textAlign: 'left',
            marginRight: '15px',
        },
        clearButton: {
            padding: '10px 15px',
            border: 'none',
            borderRadius: '15px',
            backgroundColor: 'rgba(99, 91, 255, 0.1)',
            color: config.buttonColor,
            cursor: 'pointer',
            fontSize: '16px',
            transition: 'background-color 0.3s',
            whiteSpace: 'nowrap',
        },
        chatMessages: {
            flex: 1,
            overflowY: 'auto',
            padding: config.mode === 'showcase' ? '24px' : '20px',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative', // For watermark absolute positioning
        },
        messageAgent: {
            alignSelf: 'flex-start',
            backgroundColor: 'rgba(232, 228, 255, 0.7)', // Светлый оттенок фирменного цвета
            borderRadius: config.mode === 'showcase' ? '18px 18px 18px 4px' : '15px 15px 15px 0',
            padding: config.mode === 'showcase' ? '14px 18px' : '12px 15px',
            maxWidth: '85%', // Увеличим максимальную ширину для более широких балунов
            marginBottom: config.mode === 'showcase' ? '16px' : '12px',
            wordBreak: 'normal', // Не разрывать слова без необходимости
            overflowWrap: 'break-word', // Разрывать только если слово не помещается целиком
            fontSize: config.mode === 'showcase' ? (config.showcaseMessageFontSize || '18px') : '16px',
            lineHeight: config.mode === 'showcase' ? '1.6' : '1.5',
            boxShadow: '0 2px 4px rgba(99, 91, 255, 0.15)', // Тень в фирменном цвете
            '& p': { margin: '0 0 10px 0' },
            '& p:last-child': { marginBottom: 0 },
            '& a': {
                color: `${config.linkColor || '#667eea'} !important`,
                textDecoration: 'underline !important',
                fontWeight: '500 !important',
                cursor: 'pointer !important',
            },
            '& a:hover': {
                color: `${config.linkHoverColor || '#5568d3'} !important`,
                textDecoration: 'underline !important',
            },
            '& pre': {
                backgroundColor: 'rgba(167, 91, 255, 0.08)',
                padding: '10px',
                borderRadius: '5px',
                overflowX: 'auto',
                maxWidth: '100%',
            },
            '& code': {
                fontFamily: 'monospace',
                backgroundColor: 'rgba(167, 91, 255, 0.08)',
                padding: '2px 4px',
                borderRadius: '3px',
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-all',
            },
            // '& ul, & ol': { paddingLeft: '20px' },
            '& ol': { listStyleType: 'decimal' },
            '& ul': { listStyleType: 'disc' },
            '& table': {
                borderCollapse: 'collapse',
                width: 'auto',
                maxWidth: '100%',
                overflowX: 'auto',
                display: 'block',
            },
            '& th, & td': {
                border: '1px solid rgba(99, 91, 255, 0.2)',
                padding: '8px',
                textAlign: 'left',
            },
            '& th': {
                backgroundColor: 'rgba(167, 91, 255, 0.08)',
            },
        },
        messageUser: {
            alignSelf: 'flex-end',
            backgroundColor: 'rgba(99, 91, 255, 0.9)', // Немного прозрачности
            color: 'white',
            borderRadius: config.mode === 'showcase' ? '18px 18px 4px 18px' : '15px 15px 0 15px',
            padding: config.mode === 'showcase' ? '14px 18px' : '12px 15px',
            maxWidth: '85%', // Увеличим максимальную ширину для более широких балунов
            marginBottom: config.mode === 'showcase' ? '16px' : '12px',
            wordBreak: 'normal', // Не разрывать слова без необходимости
            overflowWrap: 'break-word', // Разрывать только если слово не помещается целиком
            fontSize: config.mode === 'showcase' ? (config.showcaseMessageFontSize || '18px') : '16px',
            lineHeight: config.mode === 'showcase' ? '1.6' : '1.5',
            boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)', // Добавим легкую тень
        },
        inputContainer: {
            display: 'flex',
            borderTop: '1px solid rgba(99, 91, 255, 0.15)',
            padding: config.mode === 'showcase' ? '20px 24px' : '15px',
            paddingLeft: config.mode === 'showcase' ? '24px' : '15px',
            paddingRight: config.mode === 'showcase' ? '24px' : '15px',
        },
        chatInput: {
            flex: '1',
            padding: config.mode === 'showcase' ? '14px 18px' : '10px 15px',
            border: '1px solid rgba(99, 91, 255, 0.2)',
            borderRadius: config.mode === 'showcase' ? '24px' : '20px',
            backgroundColor: config.inputBackgroundColor || 'rgba(245, 243, 255, 0.5)',
            fontSize: config.mode === 'showcase' ? '16px' : '14px',
        },
        sendButton: {
            marginLeft: config.mode === 'showcase' ? '12px' : '10px',
            padding: config.mode === 'showcase' ? '14px 20px' : '10px 15px',
            border: 'none',
            borderRadius: config.mode === 'showcase' ? '24px' : '20px',
            background: 'radial-gradient(462.56% 102.45% at 109.47% 102.45%,#a75bff 0,#635bff 57%,#635bff 100%)',
            color: 'white',
            cursor: 'pointer',
            fontSize: config.mode === 'showcase' ? '20px' : '18px',
            transition: 'background-color 0.3s',
            minWidth: config.mode === 'showcase' ? '56px' : '48px',
        },
        preloaderContainer: {
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            zIndex: 3,
        },
        preloader: {
            width: '60px',
            height: '60px',
        },
        resizeHandle: {
            position: 'absolute',
            top: '0',
            left: '0',
            width: '20px',
            height: '20px',
            cursor: 'nw-resize',
            backgroundColor: 'rgba(99, 91, 255, 0.1)',
            borderRadius: '0 0 20px 0',
            zIndex: 1002,
        },
    };
}
