export function createStyles(config) {
    return {
        chatButton: {
            position: 'fixed',
            bottom: '20px',
            right: '20px',
            zIndex: '1000',
            padding: '15px',
            border: 'none',
            borderRadius: '25px',
            background: 'radial-gradient(462.56% 102.45% at 109.47% 102.45%,#a75bff 0,#635bff 57%,#635bff 100%)',
            color: 'white',
            cursor: 'pointer',
            fontSize: '24px',
            boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
        },
        chatContainer: {
            position: 'fixed',
            bottom: '80px',
            right: '20px',
            width: '40vw',
            height: '50vh',
            backgroundColor: 'rgba(255, 255, 255, 0.8)',
            border: `1px solid ${config.chatBorderColor}`,
            borderRadius: '20px',
            display: 'none',
            flexDirection: 'column',
            zIndex: '1001',
            overflow: 'hidden',
            fontFamily: config.fontFamily,
            fontSize: config.fontSize,
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
            backdropFilter: 'blur(10px)',
        },
        chatHeader: {
            display: 'flex',
            justifyContent: 'flex-end',
            padding: '15px',
            background: 'linear-gradient(to bottom, rgba(255,255,255,0.8) 0%, rgba(255,255,255,0) 100%)',
            backdropFilter: 'blur(5px)',
            borderBottom: '1px solid rgba(204, 204, 204, 0.5)',
            position: 'sticky',
            top: 0,
            zIndex: 2,
        },
        clearButton: {
            padding: '8px 12px',
            border: 'none',
            borderRadius: '15px',
            backgroundColor: 'rgba(99, 91, 255, 0.1)',
            color: config.buttonColor,
            cursor: 'pointer',
            fontSize: '14px',
            transition: 'background-color 0.3s',
        },
        chatMessages: {
            flex: 1,
            overflowY: 'auto',
            padding: '20px',
        },
        inputContainer: {
            display: 'flex',
            borderTop: '1px solid #ccc',
            padding: '15px',
        },
        chatInput: {
            flex: '1',
            padding: '10px',
            border: '1px solid #ccc',
            borderRadius: '20px',
            backgroundColor: config.inputBackgroundColor,
            fontSize: '14px',
        },
        sendButton: {
            marginLeft: '10px',
            padding: '10px 15px',
            border: 'none',
            borderRadius: '20px',
            background: 'radial-gradient(462.56% 102.45% at 109.47% 102.45%,#a75bff 0,#635bff 57%,#635bff 100%)',
            color: 'white',
            cursor: 'pointer',
            fontSize: '18px',
            transition: 'background-color 0.3s',
        },
        preloaderContainer: {
            position: 'absolute',
            top: '50%',
            left: '50%',
            transform: 'translate(-50%, -50%)',
            zIndex: 3,
        },
        preloader: {
            width: '60px',
            height: '60px',
        },
    };
}
